projects/projects/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webshop.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

projects/webshop/urls.py
from django.urls import path
from . import views

app_name = "webshop"

urlpatterns = [
    path('', views.homepage, name="home"),

    #category and products list
    path('category/<slug:category_slug>/', views.homepage, name="product_list_by_category"),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('all-products/', views.product_all, name="product_all"),
    path('products-by-user/<int:id>/', views.product_by_user, name="product_by_user"),

    #product add, update and delete
    path('add-product/', views.product_add, name='product_add'),
    path('edit-product/<int:id>/<slug:slug>/', views.product_update, name='product_update'),
    path('delete-product/<int:product_id>/', views.product_delete, name='product_delete'),


    #contact
    path('support/', views.contactpage, name="contact"),

    #user section
    path('register-user/', views.register, name="register"),
    path('login-user/', views.login, name="login"),
    path('logout-user/', views.logout, name="logout"),

    #user profile
    path('profile-user/<int:id>/', views.view_profile, name="view_profile"),
    path('profile-user/<int:id>/edit', views.edit_profile, name="edit_profile"),
    path('profile-user/<int:id>/delete', views.delete_profile, name="delete_profile"),

    #cart
    path('cart/', views.cart_detail, name="cart_detail"),
    path('add/<int:product_id>/', views.cart_add, name="cart_add"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
]

projects/webshop/models/category.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("webshop:product_list_by_category", args=[self.slug])

projects/webshop/models/product.py
from django.db import models
from django.urls import reverse

from . import category, user

class Product(models.Model):
    category = models.ForeignKey(category.Category, related_name='products', on_delete=models.CASCADE)
    user = models.ForeignKey(user.User, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to="products", blank=True, default="nophoto.jpg")
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("webshop:product_detail", args=[self.id, self.slug])

projects/webshop/models/user.py
from django.db import models

import hashlib, binascii, os


class User(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    username = models.CharField(max_length=40, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    password = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.first_name} {self.last_name} [{self.username}]"

    def create_hashed_password(self, password):
        salt = hashlib.sha256(os.urandom(60)).hexdigest().encode('ascii')
        pwdhash = hashlib.pbkdf2_hmac('sha512', password.encode('utf-8'), salt, 100000)
        pwdhash = binascii.hexlify(pwdhash)
        self.password = (salt + pwdhash).decode('ascii')

    def verify_password(self, password):
        salt = self.password[:64]
        stored_password = self.password[64:]
        pwdhash = hashlib.pbkdf2_hmac('sha512', 
                                  password.encode('utf-8'), 
                                  salt.encode('ascii'), 
                                  100000)
        pwdhash = binascii.hexlify(pwdhash).decode('ascii')
        return pwdhash == stored_password

    def to_dict(self):
        return {
            "id": self.id,
            "first_name": self.first_name,
            "last_name": self.last_name,
            "username": self.username,
            "email": self.email,
        }

projects/webshop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from django.db import IntegrityError
from django.core.mail import send_mail
from django.utils.text import slugify


from .models.user import User
from .models.category import Category
from .models.product import Product
from .cart import Cart


#-----------------------------HOME AND CATEGORY LIST-----------------------------#

def homepage(request: HttpRequest, category_slug=None):
    error = request.session.get("error", None)
    if error is not None:
        del request.session["error"]

    success = request.session.get("success", None)
    if success is not None:
        del request.session["success"]

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {"error": error, "success": success,  "category": category,
               "products": products, "categories": categories}
    return render(request, "webshop/homepage.html", context)


def product_detail(request, slug, id, category_slug=None):
    product = get_object_or_404(Product, slug=slug, id=id, available=True)

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {"product": product, "categories": categories}
    return render(request, "webshop/product/product_detail.html", context)


def product_all(request, category_slug=None):
    error = request.session.get("error", None)
    if error is not None:
        del request.session["error"]

    success = request.session.get("success", None)
    if success is not None:
        del request.session["success"]

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {"error": error, "success": success,  "category": category,
               "products": products, "categories": categories}
    return render(request, "webshop/product/products.html", context)


def product_by_user(request: HttpRequest, id: int, category_slug=None):
    user = get_object_or_404(User.objects, id=id)
    product_by_user = Product.objects.filter(user=user)

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {"product_by_user": product_by_user, "categories": categories}
    return render(request, "webshop/product/product_by_user.html", context)


#-----------------------------PRODUCT ADD, UPDATE AND DELETE-----------------------------#


def product_add(request: HttpRequest):
    if request.method == "GET":
        user = request.session.get("user")
        if user is not None:
            category_list = Category.objects.all()
            context = {"categories": category_list}
            return render(request, "webshop/product/product_add.html", context)
        else:
            request.session["error"] = "Ne možete da dodate proizvod dok ne napravite nalog."
            return redirect("webshop:home")
    if request.method == "POST":
        new_product = Product()
        new_product.category = Category.objects.get(
            name=request.POST["category"])
        new_product.user = User.objects.get(id=request.session["user"]["id"])
        new_product.name = request.POST["p_name"]
        new_product.image = request.FILES["img"]
        new_product.description = request.POST["description"]
        new_product.price = request.POST["price"]
        new_product.slug = slugify(new_product.name)
        new_product.save()
        return redirect("webshop:product_detail", slug=new_product.slug, id=new_product.id)


def product_update(request: HttpRequest, id: int, slug: str):
    product_by_id = Product.objects.get(id=id, slug=slug)
    if request.method == "GET":
        category_list = Category.objects.all()
        context = {"product": product_by_id, "categories": category_list}
        return render(request, "webshop/product/product_update.html", context)
    if request.method == "POST":
        product_by_id.category = Category.objects.get(
            name=str(request.POST["e_category"]))
        product_by_id.name = request.POST["e_name"]
        old_image = request.POST["old_img"]
        if "e_img" in request.FILES:
            product_by_id.image = request.FILES["e_img"]
        else:
            product_by_id.image = old_image
        product_by_id.description = request.POST["e_description"]
        product_by_id.price = request.POST["e_price"]
        product_by_id.slug = slugify(product_by_id.name)
        product_by_id.save()
        return redirect("webshop:product_detail", slug=product_by_id.slug, id=product_by_id.id)


def product_delete(request: HttpRequest, product_id: int):
    selected_product = Product.objects.get(id=product_id)
    if selected_product.user.id != request.session["user"]["id"]:
        request.session["error"] = "Nije Vam dozvoljeno da obrišete ovaj proizvod."
        return redirect("webshop:home")

    selected_product.delete()
    request.session["success"] = "Uspešno ste obrisali proizvod."
    return redirect("webshop:home")


#-----------------------------CONTACT-----------------------------#

def contactpage(request: HttpRequest, category_slug=None):
    if request.method == "GET":
        error = request.session.get("error", None)
        if error is not None:
            del request.session["error"]
        success = request.session.get("success", None)
        if success is not None:
            del request.session["success"]

        category = None
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)

        context = {"error": error, "success": success,
                   "categories": categories}
        return render(request, "webshop/contactpage.html", context)

    if request.method == "POST":
        message_subject = request.POST["subject"]
        message_email = request.POST["ct_email"]
        message = request.POST["textarea"]
        send_mail(
            message_subject,
            message,
            message_email,
            ['nemanja.ilic0000@gmail.com']
        )

        request.session["success"] = "Uspešno poslata poruka."
        return redirect("webshop:home")


#-----------------------------USER REGISTER, LOGIN, LOGOUT-----------------------------#

def register(request: HttpRequest, category_slug=None):
    if request.method == "GET":
        error = request.session.get("error", None)
        if error is not None:
            del request.session["error"]
        success = request.session.get("success", None)
        if success is not None:
            del request.session["success"]

        category = None
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)

        context = {"error": error, "success": success,
                   "categories": categories}
        return render(request, "webshop/account/register.html", context)
    if request.method == "POST":
        new_user = User()
        new_user.first_name = request.POST["first_name"]
        new_user.last_name = request.POST['last_name']
        new_user.username = request.POST["username"]
        new_user.email = request.POST["email"]
        if request.POST["password"] == request.POST["password2"]:
            new_user.create_hashed_password(request.POST['password2'])
        else:
            request.session["error"] = "Lozinke nisu iste!"
            return redirect("webshop:register")
        try:
            new_user.save()
            request.session["user"] = new_user.to_dict()
            return redirect("webshop:home")
        except IntegrityError:
            request.session["error"] = f"Korisnik sa korisničkim imenom {request.POST['username']} već postoji."
            return redirect("webshop:register")


def login(request: HttpRequest, category_slug=None):
    if request.method == "GET":
        error = request.session.get("error", None)
        if error is not None:
            del request.session["error"]
        success = request.session.get("success", None)
        if success is not None:
            del request.session["success"]

        category = None
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)

        context = {"error": error, "success": success,
                   "categories": categories}
        if "user" in request.session:
            return redirect("webshop:home")
        else:
            return render(request, "webshop/account/login.html", context)
    if request.method == "POST":
        try:
            user = User.objects.get(username=request.POST["login_username"])
            if user.verify_password(request.POST["login_password"]):
                request.session["user"] = user.to_dict()
                request.session["success"] = "Uspešno ste se prijavili."

projects/webshop/templates/webshop/account/edit_profile.html
{% extends 'webshop/_layout.html' %}
{% load static %}

{% block title %}{{request.session.user.first_name}} {{request.session.user.last_name}} | Ažuriranje profila{% endblock title %}

{% block content %}
<h3>Ažuriranje profila od {{request.session.user.first_name}} {{request.session.user.last_name}}</h3>
<br>
<form action="{% url 'webshop:edit_profile' user.id %}" method="POST">
    {% csrf_token %}
        <div class="form-group">
            <label for="e_first_name">Ime:</label>
            <input type="text" class="form-control" id="e_first_name" placeholder="Ukucajte ime" name="e_first_name" value="{{request.session.user.first_name}}" required>
            <div class="valid-feedback">Valid first name.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group">
            <label for="e_last_name">Prezime:</label>
            <input type="text" class="form-control" id="e_last_name" placeholder="Ukucajte prezime" name="e_last_name" value="{{request.session.user.last_name}}" required>
            <div class="valid-feedback">Valid last name.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group">
            <label for="e_username">Korisničko ime:</label>
            <input type="text" class="form-control" id="e_username" placeholder="Ukucajte korisničko ime" name="e_username" value="{{request.session.user.username}}" required>
            <div class="valid-feedback">Valid username.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group">
            <label for="e_email">E-pošta:</label>
            <input type="email" class="form-control" id="e_email" placeholder="Ukucajte e-poštu" name="e_email" value="{{request.session.user.email}}" required>
            <div class="valid-feedback">Valid email.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
            <input class="form-check-input" type="checkbox" name="remember" required> Slažem se da hoću da napravim izmene na svom nalogu.
            <div class="valid-feedback">Valid checkbox.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
            </label>
        </div>
        <button type="submit" class="btn btn-danger">Ažuriraj</button>
</form>
{% endblock content %}

projects/webshop/templates/webshop/account/login.html
{% extends 'webshop/_layout.html' %}
{% load static %}

{% block title %}KupujemProdajem | Logovanje{% endblock title %}

{% block content %}
<h1>Ulogujte se</h1>
    <p>Koristite formu ispod da bi ste se ulogovali:</p>
    <form action="{% url 'webshop:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="login_username">Korisničko ime:</label>
            <input type="text" class="form-control" id="login_username" placeholder="Ukucajte korisničko ime" name="login_username" required>
            <div class="valid-feedback">Valid username.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group">
            <label for="login_password">Lozinka:</label>
            <input type="password" class="form-control" id="login_password" placeholder="Ukucajte šifru" name="login_password" required>
            <div class="valid-feedback">Valid password.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <button type="submit" class="btn btn-danger">Ulogujte se</button>
        <br>
        <p>Ako nemate kreiran nalog molimo Vas <a id="links" href="{% url 'webshop:register' %}">napravite nalog</a>.</p>
    </form>   
{% endblock content %}

projects/webshop/templates/webshop/account/profile.html
{% extends 'webshop/_layout.html' %}
{% load static %}

{% block title %}{{user.first_name}} {{user.last_name}} | Profil{% endblock title %}

{% block content %}
<h3>Proizvodi od {{user.first_name}} {{user.last_name}}</h3> 
<div class="row">
    {% for prod in product_by_user %}
    <div class="col-md-4">
        <div class="card mb-2 bg-dark">
            <a href="{{ prod.get_absolute_url }}">
                <img width="100%" src="{% if prod.image %}{{prod.image.url}}{% else %}{% static 'webshop/images/products/nophoto.jpg' %}{% endif %}" />
            </a>
            <h5 class="text-center"><a href="{{prod.get_absolute_url}}" class="text-danger">{{prod.name}}</a></h5><br>
            <h5 class="text-white text-center">{{prod.price}} din</h5>
            <div class="card-body">
                <p class="card-title text-danger text-center">Proizvod od <a class="card-title text-danger" href="{% url 'webshop:view_profile' prod.user.id %}">{{prod.user.first_name}} {{prod.user.last_name}}</a></p>
                {% if prod.user.id == request.session.user.id %}
                <p class="text-center">
                    <a href="{% url 'webshop:product_update' prod.id prod.slug %}" class="btn btn-outline-danger">Ažuriraj proizvod</i></a>
                </p>
                <p class="text-center">
                    <a onclick="delete_product_confirmation(event)" href="{% url 'webshop:product_delete' prod.id %}" class="btn btn-outline-danger">Obriši proizvod</i></a>
                </p>
                {% else %}
                <p class="text-center">
                    <a href="#" class="btn btn-outline-danger">Dodaj u korpu</i></a>
                </p>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<br>
{% if request.session.user.id == user.id %}
    <h3>Profil od {{user.first_name}} {{user.last_name}}</h3>
    <button class="btn btn-mute justify-content-right" data-toggle="collapse" data-target="#frst">
        <h5>Podešavanja</h5>
    </button>
    <div id="frst" class="collapse">
        <h5>
            <a href="{% url 'webshop:edit_profile' user.id %}">Ažuriraj nalog</a>
            <a style="padding-left: 15px;" onclick="delete_user_confirmation(event)" href="{% url 'webshop:delete_profile' user.id %}">Obriši nalog</a>
        </h5>
    </div>
{% endif %}

{% endblock content %}

projects/webshop/templates/webshop/account/register.html
{% extends 'webshop/_layout.html' %}
{% load static %}

{% block title %}KupujemProdajem | Kreiranje naloga{% endblock title %}

{% block content %}
    <h1>Kreirajte naloga</h1>
    <p>Koristite formu ispod da bi ste kreirali nalog:</p>
    <form action="{% url 'webshop:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="first_name">Ime:</label>
            <input type="text" class="form-control" id="first_name" placeholder="Ukucajte ime" name="first_name" required>
            <div class="valid-feedback">Valid first name.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group">
            <label for="last_name">Prezime:</label>
            <input type="text" class="form-control" id="last_name" placeholder="Ukucajte prezime" name="last_name" required>
            <div class="valid-feedback">Valid last name.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group">
            <label for="username">Korisničko ime:</label>
            <input type="text" class="form-control" id="username" placeholder="Ukucajte korisničko ime" name="username" required>
            <div class="valid-feedback">Valid username.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group">
            <label for="email">E-pošta:</label>
            <input type="email" class="form-control" id="email" placeholder="Ukucajte e-poštu" name="email" required>
            <div class="valid-feedback">Valid email.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group">
            <label for="password">Lozinka:</label>
            <input type="password" class="form-control" id="password" placeholder="Ukucajte šifru" name="password" required>
            <div class="valid-feedback">Valid password.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group">
            <label for="password2">Potvrdite lozinku:</label>
            <input type="password" class="form-control" id="password2" placeholder="Ukucajte šifru ponovo" name="password2" required>
            <div class="valid-feedback">Valid.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
            <input class="form-check-input" type="checkbox" name="remember" required> Slažem se da hoću da kreiram svoj nalog na ovom sajtu.
            <div class="valid-feedback">Valid checkbox.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
            </label>
        </div>
        <button type="submit" class="btn btn-danger">Kreiraj nalog</button>
        <br>
        <p>Ako već imate nalog onda se <a id="links" href="{% url 'webshop:login' %}">ulogujte ovde</a>.</p>
    </form>

{% endblock content %}