projects/projects/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webshop.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

projects/webshop/urls.py
from django.urls import path
from . import views

app_name = "webshop"

urlpatterns = [
    path('', views.homepage, name="home"),

    #category and products list
    path('category/<slug:category_slug>/', views.homepage, name="product_list_by_category"),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('all-products/', views.product_all, name="product_all"),
    path('products-by-user/<int:id>/', views.product_by_user, name="product_by_user"),

    #product add, update and delete
    path('add-product/', views.product_add, name='product_add'),
    path('edit-product/<int:id>/<slug:slug>/', views.product_update, name='product_update'),
    path('delete-product/<int:product_id>/', views.product_delete, name='product_delete'),


    #contact
    path('support/', views.contactpage, name="contact"),

    #user section
    path('register-user/', views.register, name="register"),
    path('login-user/', views.login, name="login"),
    path('logout-user/', views.logout, name="logout"),

    #user profile
    path('profile-user/<int:id>/', views.view_profile, name="view_profile"),
    path('profile-user/<int:id>/edit', views.edit_profile, name="edit_profile"),
    path('profile-user/<int:id>/delete', views.delete_profile, name="delete_profile"),

    #cart
    path('cart/', views.cart_detail, name="cart_detail"),
    path('add/<int:product_id>/', views.cart_add, name="cart_add"),
    path('remove/<int:product_id>/', views.cart_remove, name="cart_remove"),
]

projects/webshop/models/category.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
        
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("webshop:product_list_by_category", args=[self.slug])

projects/webshop/models/product.py
from django.db import models
from django.urls import reverse

from . import category, user

class Product(models.Model):
    category = models.ForeignKey(category.Category, related_name='products', on_delete=models.CASCADE)
    user = models.ForeignKey(user.User, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to="products", blank=True, default="nophoto.jpg")
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("webshop:product_detail", args=[self.id, self.slug])

projects/webshop/models/user.py
from django.db import models

import hashlib, binascii, os


class User(models.Model):
    first_name = models.CharField(max_length=250)
    last_name = models.CharField(max_length=250)
    username = models.CharField(max_length=40, unique=True)
    email = models.EmailField(max_length=100, unique=True)
    password = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.first_name} {self.last_name} [{self.username}]"

    def create_hashed_password(self, password):
        salt = hashlib.sha256(os.urandom(60)).hexdigest().encode('ascii')
        pwdhash = hashlib.pbkdf2_hmac('sha512', password.encode('utf-8'), salt, 100000)
        pwdhash = binascii.hexlify(pwdhash)
        self.password = (salt + pwdhash).decode('ascii')

    def verify_password(self, password):
        salt = self.password[:64]
        stored_password = self.password[64:]
        pwdhash = hashlib.pbkdf2_hmac('sha512', 
                                  password.encode('utf-8'), 
                                  salt.encode('ascii'), 
                                  100000)
        pwdhash = binascii.hexlify(pwdhash).decode('ascii')
        return pwdhash == stored_password

    def to_dict(self):
        return {
            "id": self.id,
            "first_name": self.first_name,
            "last_name": self.last_name,
            "username": self.username,
            "email": self.email,
        }

projects/webshop/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest
from django.db import IntegrityError
from django.core.mail import send_mail
from django.utils.text import slugify


from .models.user import User
from .models.category import Category
from .models.product import Product
from .cart import Cart


#-----------------------------HOME AND CATEGORY LIST-----------------------------#

def homepage(request: HttpRequest, category_slug=None):
    error = request.session.get("error", None)
    if error is not None:
        del request.session["error"]

    success = request.session.get("success", None)
    if success is not None:
        del request.session["success"]

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {"error": error, "success": success,  "category": category,
               "products": products, "categories": categories}
    return render(request, "webshop/homepage.html", context)


def product_detail(request, slug, id, category_slug=None):
    product = get_object_or_404(Product, slug=slug, id=id, available=True)

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {"product": product, "categories": categories}
    return render(request, "webshop/product/product_detail.html", context)


def product_all(request, category_slug=None):
    error = request.session.get("error", None)
    if error is not None:
        del request.session["error"]

    success = request.session.get("success", None)
    if success is not None:
        del request.session["success"]

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    context = {"error": error, "success": success,  "category": category,
               "products": products, "categories": categories}
    return render(request, "webshop/product/products.html", context)


def product_by_user(request: HttpRequest, id: int, category_slug=None):
    user = get_object_or_404(User.objects, id=id)
    product_by_user = Product.objects.filter(user=user)

    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    context = {"product_by_user": product_by_user, "categories": categories}
    return render(request, "webshop/product/product_by_user.html", context)


#-----------------------------PRODUCT ADD, UPDATE AND DELETE-----------------------------#


def product_add(request: HttpRequest):
    if request.method == "GET":
        user = request.session.get("user")
        if user is not None:
            category_list = Category.objects.all()
            context = {"categories": category_list}
            return render(request, "webshop/product/product_add.html", context)
        else:
            request.session["error"] = "Ne možete da dodate proizvod dok ne napravite nalog."
            return redirect("webshop:home")
    if request.method == "POST":
        new_product = Product()
        new_product.category = Category.objects.get(
            name=request.POST["category"])
        new_product.user = User.objects.get(id=request.session["user"]["id"])
        new_product.name = request.POST["p_name"]
        new_product.image = request.FILES["img"]
        new_product.description = request.POST["description"]
        new_product.price = request.POST["price"]
        new_product.slug = slugify(new_product.name)
        new_product.save()
        return redirect("webshop:product_detail", slug=new_product.slug, id=new_product.id)


def product_update(request: HttpRequest, id: int, slug: str):
    product_by_id = Product.objects.get(id=id, slug=slug)
    if request.method == "GET":
        category_list = Category.objects.all()
        context = {"product": product_by_id, "categories": category_list}
        return render(request, "webshop/product/product_update.html", context)
    if request.method == "POST":
        product_by_id.category = Category.objects.get(
            name=str(request.POST["e_category"]))
        product_by_id.name = request.POST["e_name"]
        old_image = request.POST["old_img"]
        if "e_img" in request.FILES:
            product_by_id.image = request.FILES["e_img"]
        else:
            product_by_id.image = old_image
        product_by_id.description = request.POST["e_description"]
        product_by_id.price = request.POST["e_price"]
        product_by_id.slug = slugify(product_by_id.name)
        product_by_id.save()
        return redirect("webshop:product_detail", slug=product_by_id.slug, id=product_by_id.id)


def product_delete(request: HttpRequest, product_id: int):
    selected_product = Product.objects.get(id=product_id)
    if selected_product.user.id != request.session["user"]["id"]:
        request.session["error"] = "Nije Vam dozvoljeno da obrišete ovaj proizvod."
        return redirect("webshop:home")

    selected_product.delete()
    request.session["success"] = "Uspešno ste obrisali proizvod."
    return redirect("webshop:home")


#-----------------------------CONTACT-----------------------------#

def contactpage(request: HttpRequest, category_slug=None):
    if request.method == "GET":
        error = request.session.get("error", None)
        if error is not None:
            del request.session["error"]
        success = request.session.get("success", None)
        if success is not None:
            del request.session["success"]

        category = None
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)

        context = {"error": error, "success": success,
                   "categories": categories}
        return render(request, "webshop/contactpage.html", context)

    if request.method == "POST":
        message_subject = request.POST["subject"]
        message_email = request.POST["ct_email"]
        message = request.POST["textarea"]
        send_mail(
            message_subject,
            message,
            message_email,
            ['nemanja.ilic0000@gmail.com']
        )

        request.session["success"] = "Uspešno poslata poruka."
        return redirect("webshop:home")


#-----------------------------USER REGISTER, LOGIN, LOGOUT-----------------------------#

def register(request: HttpRequest, category_slug=None):
    if request.method == "GET":
        error = request.session.get("error", None)
        if error is not None:
            del request.session["error"]
        success = request.session.get("success", None)
        if success is not None:
            del request.session["success"]

        category = None
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)

        context = {"error": error, "success": success,
                   "categories": categories}
        return render(request, "webshop/account/register.html", context)
    if request.method == "POST":
        new_user = User()
        new_user.first_name = request.POST["first_name"]
        new_user.last_name = request.POST['last_name']
        new_user.username = request.POST["username"]
        new_user.email = request.POST["email"]
        if request.POST["password"] == request.POST["password2"]:
            new_user.create_hashed_password(request.POST['password2'])
        else:
            request.session["error"] = "Lozinke nisu iste!"
            return redirect("webshop:register")
        try:
            new_user.save()
            request.session["user"] = new_user.to_dict()
            return redirect("webshop:home")
        except IntegrityError:
            request.session["error"] = f"Korisnik sa korisničkim imenom {request.POST['username']} već postoji."
            return redirect("webshop:register")


def login(request: HttpRequest, category_slug=None):
    if request.method == "GET":
        error = request.session.get("error", None)
        if error is not None:
            del request.session["error"]
        success = request.session.get("success", None)
        if success is not None:
            del request.session["success"]

        category = None
        categories = Category.objects.all()
        products = Product.objects.filter(available=True)
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)

        context = {"error": error, "success": success,
                   "categories": categories}
        if "user" in request.session:
            return redirect("webshop:home")
        else:
            return render(request, "webshop/account/login.html", context)
    if request.method == "POST":
        try:
            user = User.objects.get(username=request.POST["login_username"])
            if user.verify_password(request.POST["login_password"]):
                request.session["user"] = user.to_dict()
                request.session["success"] = "Uspešno ste se prijavili."

projects/webshop/templates/webshop/_layout.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'webshop/css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'webshop/images/background/favicon.ico' %}" type="image/x-icon">

</head>
<body>

    <nav class="navbar sticky-top navbar-expand-sm bg-white navbar-white">

        <!-- Brand -->
        <a class="navbar-brand" href="{% url 'webshop:home' %}"><img src="{% static 'webshop/images/background/logo.jpg' %}" /></a>

        <!-- Button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon">
                <i class="fas fa-bars" style="color: black; font-size:28px;"></i>
            </span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webshop:home' %}"><i class="fas fa-home"></i> Početna</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webshop:contact' %}"><i class="fas fa-address-book"></i> Kontakt</a>
                </li>

                <!-- Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"><i class="fab fa-product-hunt"></i>
                        Proizvodi
                    </a>
                    <div class="dropdown-menu">
                        {% if request.session.user %}
                        <a class="dropdown-item text-secondary" href="{% url 'webshop:product_all'  %}">Svi Proizvodi</a>
                        <a class="dropdown-item text-secondary" href="{% url 'webshop:product_add' %}">Dodaj Proizvod</a>
                        <a class="dropdown-item text-secondary" href="{% url 'webshop:product_by_user' request.session.user.id %}">Vaši Proizvodi</a>
                        {% else %}
                        <a class="dropdown-item text-secondary" href="{% url 'webshop:product_all'  %}">Svi Proizvodi</a>
                        {% endif %}
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown"><i class="fas fa-store"></i>
                        Kategorije
                    </a>
                    <div class="dropdown-menu scrollable-menu" role="menu">
                    {% for cat in categories %}
                        <a class="dropdown-item text-secondary" href="{{cat.get_absolute_url}}">{{ cat.name }}</a>
                    {% endfor %}
                    </div>
                </li>
            </ul>



            <div class="navbar-nav navbar-collapse justify-content-end">
                
                {% if request.session.user %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webshop:view_profile' request.session.user.id %}"><i class="fas fa-user-circle"></i>  Profil</a>
                </li>
                <li class="nav-item">
                    <a onclick="logout_confirmation(event)" class="nav-link" href="{% url 'webshop:logout' %}"><i class="fas fa-sign-in-alt"></i>  Izađi</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webshop:register' %}"><i class="fas fa-user-plus"></i>  Kreiraj nalog</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webshop:login' %}"><i class="fas fa-user"></i>  Uloguj se</a>
                </li>
                {% endif %}
            </div>
        </div>
    </nav>

    <div id="subheader">
        <div class="cart">
            <a href="{% url 'webshop:cart_detail' %}"><i class="fas fa-shopping-basket fa-2x"></i></a>
        </div>
    </div>

    <div class="container border border-light rounded-bottom">

        {% if error %}
        <div class="alert alert-dark alert-dismissible">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong class="text-danger">{{ error }}</strong>
        </div>
        {% endif %}

        {% if success %}
        <div class="alert alert-dark alert-dismissible">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong class="text-success">{{ success }}</strong>
        </div>
        {% endif %}


        <!-- OVDE IDE PROIZVOD -->
        {% if category %}
        <h3>{{category.name}}</h3><br>
        <div class="row">
            {% for prod in products %}
            <div class="col-md-4">
                <div class="card mb-2 bg-dark" style="width: auto; height: auto;">
                    <a href="{{ prod.get_absolute_url }}">
                        <img class="card-img-top" src="{% if prod.image %}{{prod.image.url}}{% else %}{% static 'webshop/images/products/nophoto.jpg' %}{% endif %}" />
                    </a>
                    <div class="card-body">
                        <h5 class="text-center"><a href="{{prod.get_absolute_url}}" class="text-danger">{{prod.name}}</a></h5><br>
                        <h5 class="text-white text-center">{{prod.price}} din</h5>
                    
                        <p class="card-title text-danger text-center">Proizvod od <a class="card-title text-danger" href="{% url 'webshop:view_profile' prod.user.id %}">{{prod.user.first_name}} {{prod.user.last_name}}</a></p>
                        <p class="text-center">
                            <a href="{% url 'webshop:cart_add' product_id=prod.id %}" class="btn btn-outline-danger">Dodaj u korpu</i></a>
                        </p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}

            {% block pre-content %}{% endblock pre-content %}
            {% block content %}{% endblock content %}
        {% endif %}

        
        <footer>
        <br>
        <h4 class="text-primary">
        <strong>
            <span style="color: #ed280e;">Ku</span><span style="color: #e6c809;">pu</span><span style="color: #34c90a;">je</span><span style="color: #0e67ed;">m</span><span style="color: darkblue;">Prodajem</span>
        </strong>&reg;</h4>
        <p>Uvek tu za vas.</p> 
        <p>&copy; 2021 KupujemProdajem. Sav materijal je korišćen u edukativne svrhe.</p>
        <a id="instagram" href="https://www.instagram.com/ilicnemanjaaa/" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
        <a id="whatsapp" href="https://wa.me/0604244986" target="_blank"><i class="fab fa-whatsapp fa-2x"></i></a>
        <a id="github" href="https://github.com/nemanjailic7" target="_blank"><i class="fab fa-github fa-2x"></i></a>
        <a id="linkedin" href="https://www.linkedin.com/in/nemanja-ili%C4%87-b018a61ba/" target="_blank"><i class="fab fa-linkedin fa-2x"></i></a>
        <br>
    </footer>

    </div>


    <script src="{% static 'webshop/js/index.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

projects/webshop/templates/webshop/contactpage.html
{% extends 'webshop/_layout.html' %}
{% load static %}

{% block title %}KupujemProdajem | Podrška{% endblock title %}

{% block content %}
<h1>Podrška</h1>
    <p>Koristite formu ispod da bi ste nas kontaktirali putem e-pošte:</p>
    <form action="{% url 'webshop:contact' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="ct_email">E-pošta:</label>
            <input type="email" class="form-control" id="ct_email" placeholder="Ukucajte e-poštu" name="ct_email" required>
            <div class="valid-feedback">Valid email.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group">
            <label for="subject">Naslov poruke</label>
            <input type="text" class="form-control" id="subject" placeholder="Ukucajte naslov" name="subject" required>
            <div class="valid-feedback">Valid subject.</div>
            <div class="invalid-feedback">Molimo Vas popunite ovo polje.</div>
        </div>
        <div class="form-group">
            <label for="textarea">Poruka</label>
            <textarea class="form-control" id="textarea" name="textarea" rows="3" placeholder="Ukucajte poruku" required></textarea>
            <div class="valid-feedback">Valid textarea.</div>
            <div class="invalid-feedback">Please fill out this field.</div>
        </div>
        <button type="submit" class="btn btn-danger">Pošaljite</button>
    </form> 
{% endblock content %}

projects/webshop/templates/webshop/homepage.html
{% extends 'webshop/_layout.html' %}
{% load static %}
{% load i18n %}

{% block title %}KupujemProdajem&reg;{% endblock title %}

{% block pre-content %}
{% if not request.session.user %}
<h3 class="text-center">Dobrodošli na sajt 
    <strong>
        <span style="color: #ed280e;">Ku</span><span style="color: #e6c809;">pu</span><span style="color: #34c90a;">je</span><span style="color: #0e67ed;">m</span><span style="color: darkblue;">Prodajem</span>
    </strong>
</h3>
<p class="text-center">Uvek tu za vas.</p>

<div class="container">
    <div id="demo" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ul class="carousel-indicators">
            <li data-target="#demo" data-slide-to="0" class="active"></li>
            <li data-target="#demo" data-slide-to="1"></li>
            <li data-target="#demo" data-slide-to="2"></li>
            <li data-target="#demo" data-slide-to="3"></li>
            <li data-target="#demo" data-slide-to="4"></li>
            <li data-target="#demo" data-slide-to="5"></li>
        </ul>

        <!-- The slideshow -->
        <div class="carousel-inner">
            <div class="carousel-item active">
            <img width="1000" height="600" src="{% static 'webshop/images/background/img1.jpeg' %}" alt="img1">
            </div>
            <div class="carousel-item">
            <img width="1000" height="600" src="{% static 'webshop/images/background/img2.jpeg' %}" alt="img2">
            </div>
            <div class="carousel-item">
            <img width="1000" height="600" src="{% static 'webshop/images/background/img3.jpeg' %}" alt="img3">
            </div>
            <div class="carousel-item">
            <img width="1000" height="600" src="{% static 'webshop/images/background/img4.jpeg' %}" alt="img3">
            </div>
            <div class="carousel-item">
            <img width="1000" height="600" src="{% static 'webshop/images/background/img5.jpeg' %}" alt="img3">
            </div>
            <div class="carousel-item">
            <img width="1000" height="600" src="{% static 'webshop/images/background/img6.jpeg' %}" alt="img3">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="carousel-control-prev" href="#demo" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#demo" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</div>
{% endif %}
{% endblock pre-content %}

{% block content %}
{% if request.session.user %}
    <h1>Dobrodošli {{request.session.user.first_name}} {{request.session.user.last_name}}</h1>
    <br>
{% else %}
    <h5>
        KupujemProdajem je mesto gde možete da kupite šta god poželite. Možete kreirati nalog i prodati neki proizvod ili kupiti isti.
    </h5>
    <br>
    <h5>Ako samo želite da kupite nešto onda Vam ne treba nalog, možete to uraditi <a id="links" href="{% url 'webshop:product_all'  %}">ovde</a>.</h5>
    <br>
    <h5>Nemate nalog?</h5>
    <p>Kreirajte nalog <a id="links" href="{% url 'webshop:register' %}">ovde</a>.</p>
    <br>
    <h5>Ako imate bilo kakvih problema kontaktirajte našu podršku:</h5>
    <p><a id="links" href="{% url 'webshop:contact' %}">Kontakt</a></p>
{% endif %}
{% endblock content %}